Switch from Unit of work to Services.
Sputnavi/BicycleCompany.API pull request #5
Opened 2021-07-20 14:23 UTC by Sputnavi

I have doubts about my implementation of services.

2021-07-26 08:10 UTC, AnnaGolosova commented on BicycleCompany.Models/Response/PartProblemForReadModel.cs
> +        public PartForReadModel Part { get; set; }
Let it be `PartDetailsModel`

2021-08-07 20:32 UTC, AnnaGolosova requested changes

2021-08-07 20:32 UTC, AnnaGolosova commented on BicycleCompany.BLL/appsettings.json
> +    "key": "bicycle!company!secret!key!"
Move all secret values from project setting to environment settings. In the future, we will use some secret storage for this, like Azure KeyVault, to GitHub secrets.

2021-08-07 20:32 UTC, AnnaGolosova commented on BicycleCompany.Tests/ProblemsControllerTests.cs
> +            Assert.IsType<OkObjectResult>(result);
You should also check here that you get an empty list.

2021-08-07 20:32 UTC, AnnaGolosova commented on BicycleCompany.Tests/ProblemsControllerTests.cs
> +            Assert.IsType<OkObjectResult>(result);
And check that result is not null

2021-08-07 20:32 UTC, AnnaGolosova commented on BicycleCompany.Tests/ProblemsControllerTests.cs
> +            Assert.IsType<List<ProblemForReadModel>>(result.Value);
I can suggest using FluentAssertions for all asserts https://fluentassertions.com/  
At least you can try to use it for some tests, no need to replace old implementation for all tests

2021-08-07 20:32 UTC, AnnaGolosova commented on BicycleCompany.Tests/ProblemsControllerTests.cs
> +            Assert.Equal(problems.Count, GetFakeProblemList().Count);
You need to check here ALL fields of ALL items. To ensure that controller returns values in the correct format, and doesn't modify it.

2021-08-07 20:32 UTC, AnnaGolosova commented on BicycleCompany.Tests/ProblemsControllerTests.cs
> +            Assert.IsType<ProblemForReadModel>(result.Value);
Same comment. Always check all data that you can

2021-08-07 20:32 UTC, AnnaGolosova commented on BicycleCompany.Tests/ProblemsControllerTests.cs
> +            await Assert.ThrowsAsync<ArgumentException>(async () =>
You should check all error messages here

2021-08-07 20:32 UTC, AnnaGolosova commented on BicycleCompany.Tests/ProblemsControllerTests.cs
> +        public async Task DeletePartForProblem_ShouldReturnNoContent_WithValidId()
Please, order all your tests. and better, move all Delete... tests to a separate region. It makes me crazy to jump through all this file to find more tests about Delete... method

2021-08-07 20:32 UTC, AnnaGolosova commented on BicycleCompany.Tests/ProblemsControllerTests.cs
> +        public async Task DeleteProblem_ShouldReturnNoContent_WithValidId()
What's the difference between this test and `DeletePartForProblem_ShouldReturnNoContent_WithValidId` test?

2021-08-09 06:49 UTC, Sputnavi commented on BicycleCompany.Tests/ProblemsControllerTests.cs
> +        public async Task DeleteProblem_ShouldReturnNoContent_WithValidId()
The difference is that these tests for different methods of controller. `DeleteProblem` is used to delete a Problem and `DeletePartForProblem` deletes a part from Problem note.

2021-08-09 06:57 UTC, Sputnavi commented on BicycleCompany.Tests/ProblemsControllerTests.cs
> +        public async Task DeletePartForProblem_ShouldReturnNoContent_WithValidId()
Main answer below. I order my tests by Method Name. I think it's ok :)
So should I use `#Region` to separate tests?

2022-02-02 18:38 UTC, closed without merging